language: python
python:
  - "3.6"
cache: pip

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.48/hugo_0.48_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - pip install Pygments
  - rm -rf public 2> /dev/null

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  verbose: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master

notifications:
  email:
    on_success: never
