baseURL: ""
relativeurls: true
languageCode: en-us
title: Technical Notes
theme: tnotes.theme
enableEmoji: true

params:
  subdomain: ""
  home: "https://www.anncudis.com/"
  cv: "https://www.anncudis.com/programmer/cv/"
