baseURL: ""
relativeurls: true
languageCode: en-us
title: My New Hugo Site
theme: tnotes.theme

links:
  home: "https://www.anncudis.com/"
  cv: "https://www.anncudis.com/programmer/cv/"

params:
  subdomain: ""
