baseURL: "/tnotes"
relativeurls: true
languageCode: en-us
title: Technical Notes
theme: tnotes.theme

links:
  home: "https://www.anncudis.com/"
  cv: "https://www.anncudis.com/programmer/cv/"

params:
  subdomain: "/tnotes"
